"""For each of the new outlier motions, inspect the actual stored rot_velocity
in the GT 263 to see if it ever exceeds π/2 (which would mean our wrap fix
is over-aggressive)."""
import sys, numpy as np
if not hasattr(np, 'float'): np.float = float
if not hasattr(np, 'int'): np.int = int
sys.path.insert(0, '/home/jungbin_cho/HumanML3D')

outliers = ['M006545', '003574', 'S_M004498', 'M006904']
PI_HALF = np.pi / 2

print(f'{"motion":15s}  {"rot_vel min":>12s}  {"rot_vel max":>12s}  {"|rot_vel| max":>12s}  {"|>π/2| count":>12s}')
for mid in outliers:
    hml = np.load(f'/home/jungbin_cho/HumanML3D/HumanML3D/new_joint_vecs/{mid}.npy')
    rv = hml[:, 0]
    print(f'{mid:15s}  {rv.min():12.4f}  {rv.max():12.4f}  {np.abs(rv).max():12.4f}  {(np.abs(rv) > PI_HALF).sum():12d}')

# Also check the relative rotation magnitude that would be generated by HML3D's
# encoder for these motions, to see if there's a real >π physical rotation.
print()
print('Implied per-frame physical rotation (2*|rot_vel|, in deg):')
for mid in outliers:
    hml = np.load(f'/home/jungbin_cho/HumanML3D/HumanML3D/new_joint_vecs/{mid}.npy')
    rv = hml[:, 0]
    max_deg = float(np.degrees(2 * np.abs(rv).max()))
    print(f'  {mid}: max ≈ {max_deg:.1f}° per frame  (at 20fps ≈ {max_deg*20:.0f} deg/sec)')
